//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int PostId { get; set; }
        public string Post { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual User User { get; set; }
    }
}
