//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieId { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public System.DateTime LaunchDate { get; set; }
    }
}
